### PR TITLE
Avoid blocking or failing when attempting to project files

### LINKED ISSUE #72: Detect and set projection state on read-only files
The github/VFSForGit#23 issue stems from an internal issue whereby the `git add` command first creates a temporary file (e.g., `.git/objects/19/tmp_obj_wdSBSa`) with read-only file permissions, and then requests a hard link be created to another path (e.g., `.git/objects/19/0a18037c64c43e6b11489df4bf0b9eb6d2c9bf`).

The `projfs_op_link()` operation begins by making sure all the parent directories and the source file are fully projected, and in particular, [calls `project_file()`](https://github.com/github/libprojfs/blob/6aec7117b2744dad27cf771840a0dcff473b2b0d/lib/projfs.c#L568) on the source path.  This in turn [calls `acquire_proj_state_lock()`](https://github.com/github/libprojfs/blob/6aec7117b2744dad27cf771840a0dcff473b2b0d/lib/projfs.c#L465) with the `O_RDWR` flag because we are hoping to be notified if the path actually corresponds to a directory; in such a case, the `openat(2)` that function would return `EISDIR`.

Because the source file is read-only, however, the `openat(2)` fails with `EACCES`, upon receipt of which the `op_link` operation pre-emptively returns with an error.

Simulating this behaviour is straightforward on a test mount; it occurs not only on hard link operations but move/rename as well:
```
% touch FOO
% chmod 444 FOO
% ln FOO BAR
ln: failed to create hard link 'BAR' => 'FOO': Permission denied
% mv FOO BAR
mv: cannot move 'FOO' to 'BAR': Permission denied
```

Furthermore, our call to `fsetxattr(2)` will fail on read-only files, which inhibits our ability to set (and remove) our projection state flag.

We likely need to implement `acquire_proj_state_lock()` by only opening files with `O_RDONLY`, acquiring our `flock(2)`, then testing with `fstat(2)` to determine if the file is not a regular file, and also setting/resetting file permissions, if necessary, around our `fsetxattr(2)` call.

---
As a side note, along with the challenges we've encountered in performing locking around projection state transitions (which would ideally be handled within our inode structures instead of with `flock()`), this may be another case where having low-level FUSE API access, or kernel-level access, would be valuable.

### PR DESCRIPTION
**Pull request by chrisd8088**
When any file happens to have read-only permissions, any file operation which calls `project_file()` to ensure it has been populated with content (such as `open(2)` and many others) will fail, because we try to open the file with `O_RDWR`.  Instead, we now only require read permissions and open the file with `O_RDONLY` when acquiring a lock on it in `project_file()`.  If the file needs to be populated, we then re-open it with `O_WRONLY`, after temporarily adding user write permission with `fchmod(2)` if necessary.  Similarly, if we determine that a directory needs to be populated in `project_dir()`, we temporarily add user write permissions if necessary.

We only check user write permissions (`S_IWUSR`) because, if the file or directory is not owned by the current effective user, then `fchmod()` would fail anyway (assuming we're not a privileged user), so we wouldn't be able to add any additional permissions, and if the file or directory _is_ owned by the current effective user, then only `S_IWUSR` is checked when determining access since only the [best-matching class's permissions are checked](https://en.wikipedia.org/wiki/File_system_permissions#Classes) and there is no fall-through to other classes (i.e., `S_IWGRP` or `S_IWOTH`).  And since we are running a FUSE filesystem without the `allow_other` option, we can generally expect to [not be running](https://github.com/libfuse/libfuse#security-implications) as `root` or in a privileged state.

Therefore our `fchmod_user_write()` helper function therefore has a simplified version of the `uid` and mode tests [implemented](https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/sysv/linux/faccessat.c;h=a5891f43c299b107ee50af7e91d72df4c4a1bee2;hb=HEAD#l59) for glibc's `faccessat(2)` function.

When creating empty files or directories as placeholders in the `projfs_create_proj_file/dir()` functions, we also want to ensure that we have, at least temporarily, write permissions, so the `fsetxattr()` calls succeed.

We always open file descriptors using `O_NONBLOCK` to ensure that if the inode actually happens to be a FIFO, we won't block indefinitely until some data is written to the pipe.  If this happens, the process which happened to trigger the projection, perhaps by innocently trying to read a not-yet-projected empty file, will enter the dreaded uninterruptable state while it waits for its syscall to complete.

We should not follow symlinks when projecting or setting/reading projection xattrs, as the symlink may be broken, or lead out of our mount point.

Separately, make our use of libfuse's headers completely internal; there is no need to require our clients to include them, as our API is independent.

Resolves #72, resolves github/VFSForGit#23.

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -10,7 +10,7 @@
 /configure
 /depcomp
 /include/config.h
-/include/config.h.in
+/include/config.h.in*
```
Comment (kivikakk) [inline .gitignore]: So long, untracked `config.h.in~`!

File: lib/projfs.c [hunk 2]
```diff
@@ -624,50 +663,90 @@ static int project_dir(const char *op, const char *path, int parent)
...
+		res = errno;
+		reset_mode = fchmod_user_write_stat(lock_fd, &st, 1);
+		if (!reset_mode)
+			goto out_release;
+		fd = open(self_fd_path, O_WRONLY | O_NONBLOCK);
+		if (fd == -1) {
+			res = errno;
+			goto out_release;
+		}
+	}
```
Comment (kivikakk) [inline lib/projfs.c]: `res` will carry the `errno` value (set on line 710) all the way to the end of the function without being reset. This leads to the `EACCES` from our failed `open` on 708 being propagated to the caller (despite successfully adding and removing the `IWUSR` bit), as seen in this example using `test_simple`:

```console
$ ls -la ~/mount/
total 12
drwxr-xr-x  2 kivikakk kivikakk 4096 Jun  5 14:20 ./
drwxr-xr-x 26 kivikakk kivikakk 4096 Jun  5 14:17 ../
-r--r--r--  1 kivikakk kivikakk    6 May 21 12:25 hi
$ cat ~/mount/hi
cat: /home/kivikakk/mount/hi: Permission denied
$
```

We may want this:

```suggestion
		res = 0;
	}
```

I found this because curiosity provoked me trying this, which still fails on this branch:

```diff
diff --git a/t/t000-mirror-read.t b/t/t000-mirror-read.t
index bbdbcd7..078396b 100755
--- a/t/t000-mirror-read.t
+++ b/t/t000-mirror-read.t
@@ -33,7 +33,8 @@ test_expect_success 'create source tree' '
        echo file1 > source/f1.txt &&
        echo file2 > source/f2.txt &&
        echo file1 > source/d1/f1.txt &&
-       echo file2 > source/d1/d2/f2.txt
+       echo file2 > source/d1/d2/f2.txt &&
+       chmod 444 source/f1.txt
 '

 test_expect_success 'check target tree structure' '
```

With the above suggestion, the test passes. We probably want to add some dedicated tests for this case, as well as a FIFO test.

Comment (chrisd8088) [reply lib/projfs.c]: Great catch, thank you!  👍

File: docs/design.md [hunk 3]
```diff
@@ -512,6 +512,22 @@ instead of in kernel mode.
...
+Whereas an in-kernel implementation may read and set attributes in
+the `trusted.*` namespace, and do so at will, a user-space filesystem
+is restricted to the use of the `user.*` extended attribute namespace,
+and, further, can only read and change attributes as allowed by the file
+permission modes of a given inode.  Thus in order to test whether
+a given file or directory is a placeholder, the user must have read
+permission, so a write-only file mode like `0222` can not be permitted.
+And user write permissions must be assigned to any read-only files or
+directories, at least temporarily, in order to convert them from the
+placeholder state to another (i.e., hydrated or full).
```
Comment (kivikakk) [inline docs/design.md]: 👍

File: lib/projfs.c (hunk 2 above)
Comment (chrisd8088) [reply lib/projfs.c]: Also, looking closely, there's an oversight a bit earlier too -- this should have a `>=`:
```
if (state_lock.state == state)
```
While writing the test scripts, I began to wonder, why is this non-projected file even trying to be opened for writing here?  Sigh.

Comment (kivikakk) [reply lib/projfs.c]: I think using any operator other than equality/inequality on enums is an antipattern -- what if we add another value that semantically makes no sense here? It's a bit awkward given the RHS is an argument though ... _scratches head_

**Comment by chrisd8088** [comment]
I've added some basic tests, which cover a number of the key changes here, but a more expansive set of tests will have to wait until I can land the `xattr-metadata-tests` branch and then the `projection-test-lists-wip` branches.  Ah, the joys of technical debt.

File: lib/projfs.c (hunk 2 above)
Comment (chrisd8088) [reply lib/projfs.c]: Switched to a more explicit `state_lock.state == state || state_lock.state == PROJ_STATE_MODIFIED`.
